# Generated by Django 4.2.11 on 2024-05-12 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_sportevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stations.appuser'),
        ),
    ]
